messagingApp/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic.base import RedirectView
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('pages/', include('pages.urls')),
    path('profiles/', include('profiles.urls')),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico"))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views
from .views import (
    PostUpdateView,
    PostDetailView,
    PostDeleteView,
    PostCreateView,
    HomePageView,
    CommentCreateView,
    like_post,
    my_view,
)

app_name = "pages"

urlpatterns = [
    path('home/', 
        HomePageView.as_view(), name='home'),
    path('<uuid:pk>/edit/',
        PostUpdateView.as_view(), name='post_edit'),

    path('<uuid:pk>',
        PostDetailView.as_view(), name='post_detail'),

    path('<uuid:pk>/delete/',
        PostDeleteView.as_view(), name='post_delete'),

    path('new/', PostCreateView.as_view(), name='post_new'),
    path('history/', views.my_view, name='post_history'),
    path('post/<uuid:post_id>/comment/create/',CommentCreateView.as_view(), name='comment_create'),
    path('post/<uuid:uuid>/like/', like_post, name='like_post'),
    path('history/', views.my_view, name='my_view'),
    path('<uuid:pk>/', PostDetailView.as_view(), name='post_detail'),

    ]

    #views.showIP

profiles/urls.py
from django.urls import path
from .views import profile_view

app_name = 'profiles'

urlpatterns = [
path('<str:username>/', profile_view, name='profile_view'),
]

pages/models.py
import uuid
from accounts.models import CustomUser
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth import get_user_model
from django.shortcuts import redirect


class PostType(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default= uuid.uuid4,
        editable=True),
    name = models.CharField(max_length=250, unique=True)

    class Meta:
        ordering =('name',)
        verbose_name = 'type'
        verbose_name_plural ="types"
    
    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

    def __str__(self):
        return self.name

STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class UserPost(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    posttype = models.ForeignKey(PostType, on_delete=models.CASCADE)
    username = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    text = models.TextField(max_length=250)
    image = models.ImageField(upload_to="userPost", blank=True)
    likes = models.DecimalField(blank=True,max_digits=9999999,decimal_places=0, null=True)
    commentCount = models.DecimalField(blank=True,max_digits=9999999,decimal_places=0, null=True)
    postTime = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    edited = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    status = models.IntegerField(choices=STATUS, default=0)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)


    class Meta:
        ordering =('-postTime',)
        verbose_name = 'userpost'
        verbose_name_plural ="userposts"
    
    def get_absolute_url(self):
        return redirect(reverse('pages:post_history'))
    def __str__(self):
        return self.text

class PostLike(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    post = models.ForeignKey(UserPost, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'post')

class Comment(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    post = models.ForeignKey(UserPost, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    comment = models.TextField(max_length=250)
    image = models.ImageField(upload_to="userPost", blank=True)
    likes = models.DecimalField(blank=True,max_digits=9999999,decimal_places=0, null=True)
    postTime = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    edited = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ('-postTime',)

    def str(self):
        return self.comment

    def get_absolute_url(self):
        return reverse('pages:post_history', args=[str(self.post.id)])

profiles/models.py
import uuid
from accounts.models import CustomUser
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth import get_user_model
from django.shortcuts import redirect

class Profile(models.Model):
    username = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    bio = models.TextField(max_length=300, blank=True ,default="Nothing yet!")
    location = models.CharField(max_length=30, blank=True , default="Unknown")

    def __str__(self):
        return self.bio

profiles/views.py
from django.shortcuts import render, get_object_or_404
from .models import Profile
from accounts.models import CustomUser
from django.contrib.auth import get_user_model


from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth import get_user_model
from .models import Profile
from pages.models import UserPost

@receiver(post_save, sender=get_user_model())
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(username=instance)

def profile_view(request, username):
    User = get_user_model()
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, username_id=user)
    post_list = UserPost.objects.filter(username=user)
    context = {'user': user, 'profile': profile, 'post_list': post_list}
    return render(request, 'profile.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body class="bgc0">
  <div class="container ">
      <div class="container-fluid ">
          <div class="row g-0">
              <div class="col-lg-2 border-end border-primary">
                  {% include 'navbar_side.html' %}
              </div>
              <div class="col-lg-6 ">
                {% include 'navbar.html' %}
                <div class="my-4">
                  {% block content %}
                  {% endblock %}
                </div>
              </div>
              <div class="col-lg-2 border-start border-primary">
              </div>
          </div>
      </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</html>

templates/comment_create.html
{% extends 'base.html' %}
{% block content %}
  <h1>New comment</h1>
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success ml-2" type="submit">Save</button>
  </form>
{% endblock content %}

templates/comment_detail.html
{% extends 'base.html' %}
{% block content %}
  <h1>New comment</h1>
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success ml-2" type="submit">Save</button>
  </form>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
HOME
{% endblock content %} 

templates/navbar.html
<!-- navbar.html -->

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
<div class="container">
  <div class="row">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary ">
      <div class="container">
        <a class="navbar-brand display-6" href="{% url 'pages:home' %}">Pages <span class="bi bi-file"></span></a>
        <button class="navbar-toggler"  type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
            <li class="nav-item ">
              <a class="nav-link" href="{% url 'pages:home' %}">Home <span class="bi bi-house"></span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pages:post_history' %}">Posts <span class="bi bi-newspaper"></span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pages:post_new' %}">New Post <span class="bi bi-file-plus"></span></a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <nav class="navbar navbar-expand-lg navbar-light border-bottom border-primary">
      <div class="container d-flex justify-content-center">
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
          <ul class="navbar-nav flex-fill">
            <li class="nav-item flex-grow-1">
              <a class="nav-link text-center" href="#">For you</a>
            </li>
            <li class="nav-item flex-grow-1">
              <a class="nav-link text-center" href="#">Following</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</div>

templates/navbar_side.html
<!-- top_navbar.html -->

<div class="container">
    <div class="row">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-4 pt-3 text-white min-vh-100">
                <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <span class="fs-5 d-none d-sm-inline">Menu</span>
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <li class="nav-item">
                        <a href="#" class="nav-link align-middle px-0">
                            <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span>
                        </a>
                    </li>
                    <li>
                        <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi bi-newspaper"></i> <span class="ms-1 d-none d-sm-inline">Posts</span> </a>
                        <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                            <li class="w-100">
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">New Posts</span></a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">For You</span></a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#submenu2" data-bs-toggle="collapse" class="nav-link px-0 align-middle ">
                            <i class="fs-4 bi bi-calendar2-event"></i> <span class="ms-1 d-none d-sm-inline">Events</span></a>
                        <ul class="collapse nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">
                            <li class="w-100">
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Local</span></a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Global</span></a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link align-middle px-0">
                            <i class="fs-4 bi-person"></i> <span class="ms-1 d-none d-sm-inline">Settings</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link align-middle px-0">
                            <i class="fs-4 bi-pencil-square"></i> <span class="ms-1 d-none d-sm-inline">New Post</span>
                        </a>
                    </li>
                </ul>
                <hr>
                <div class="dropdown pb-4">
                    {% if user.is_authenticated %}
                      <a href="#" class="d-flex align-items-center text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{{ user.avatar.url }}" alt="{{ user.username }}'s avatar" width="60" height="60" class="rounded-circle">
                        <span class="d-none d-sm-inline mx-1">{{ user.username }}</span>
                      </a>
                      <ul class="dropdown-menu dropdown-menu text-small shadow" aria-labelledby="dropdownUser1">
                        <li><a class="dropdown-item" href="#">Settings</a></li>
                        <li><a class="dropdown-item" href="{% url 'profiles:profile_view' username=user.username %}">Profile</a></li>
                        <li>
                          <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'signout' %}">Sign out</a></li>
                      </ul>
                    {% else %}
                      <a href="{% url 'signin' %}" class="btn btn-primary">Log in</a>
                    {% endif %}
                  </div>
            </div>
        </div>
    </div>
</div>

templates/post.html
{% extends 'base.html' %}
{% block title %}pages{% endblock title %}
{% block content %}
<p>3</p>
<!-- Blog Entries Column -->
<div class="col-md-8 mt-3 left">
    {% for user in object_list  %}
            <p>{{user.text }}</p>
        </div>
   {% endfor %}   
{% endblock content %}

templates/post_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
  <div class="card-header">
  <h1>Delete</h1>
</div>
<div class="card-body">
  <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ post.title }}"?</p>
  </div>
  <div class="card-footer">
    <button class="btn btn-danger ml-2" type="submit">Confirm</button>
  </form>
</div>
{% endblock content %}

templates/post_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="article-entry mx-auto" style="width:500px">
      <div class="justify-content-center">
        <div class="card">
          <div class="card-header">
          <div class ="row">
            <div class="col" >
            <p>by {{ user.username }} | {{ userpost.postTime }}</p>
            </div>
            <div class="col-md-2 offset-md-4">
            <p><a href="{% url 'pages:post_edit' userpost.pk %}">Edit</a>
              {% if user.username %} |
              <a href="{% url 'pages:post_delete' userpost.pk %}">Delete</a>
              {% endif %}
            </p>
            </div>
            </div>
          </div>
          <div class="card-body">
          {% if userpost.image %}
          <img class = "post py-1" src="{{userpost.image.url}}" alt="{{ userpost.text }}">
          {% endif %}
          <p>{{ userpost.text }}</p>
          </div>
          <div class="card-footer">
            <p><a href="{% url 'pages:comment_create' post_id=userpost.pk  %}">Comment ...</a></p>
            {% for comment in comments %}
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ comment.author }}</h5>
                    <p class="card-text">{{ comment.comment }}</p>
                </div>
            </div>
          {% endfor %}
          <p><a href="{% url 'pages:post_history' %}">Go back ...</a></p>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/post_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="card">
  <div class="card-header">
  <h1>Edit</h1>
</div>
<div class="card-body">
  <form action="" method="post">{% csrf_token %}
    {{ form|crispy}}
  </div>
  <div class="card-footer">
    <button class="btn btn-primary ml-2" type="submit">Update</button>
  </form>
</div>
{% endblock %}

templates/post_list.html
{% extends 'base.html' %}
{% block title %}Articles{% endblock title %}
{% block content %}
{% if user.is_authenticated %}
<input type="hidden" name="latitude" id="id_latitude">
<input type="hidden" name="longitude" id="id_longitude">
  {% for post in post_list %}
  <div  class="col d-flex justify-content-center my-4">
  <div class="card w-80 p- ">
    {% if post.image %}
      <img class="card-img-top" src="{{post.image.url}}" alt="Card image cap">
    {% endif %}
    <div class="card-body">
      <div class="row">
        <div class="col align-self-start">
          <img class="rounded-circle" src="{{ user.avatar.url }}" alt="{{ user.username }}" width="60px" height="60px">
        </div>
        <div class="col text-left">
          <h5 class="card-title"><a href="{% url 'profiles:profile_view' username=post.username %}" style="text-decoration:none;">{{post.username}}</a></h5>
        </div>
      </div>
      <p class="card-text">{{post.text}}</p>
      <div class="card-footer">
        <div class="container text-center">
          <div class="row">
            <div class="col">
              <form action="{% url 'pages:like_post' post.pk %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-light">Likes {{post.likes|default:"0"}}</button>
              </form>
            </div>
            <div class="col">
              <button type="submit" class="btn btn-light">Repost 0</button>
            </div>
            <div class="col">
              <button type="submit" class="btn btn-light" > <a href="{% url 'pages:post_detail' post.pk %} "style="text-decoration: none; color: inherit;" >Comments 0</a></button>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
  </div>

  {% endfor %}
{% else %}
  <p class="col d-flex justify-content-center my-4">You must be logged in to view posts.</p>
{% endif %}
{% endblock %}

<script>
  function sendLocationOnLoad() {
    console.log("test")
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        var latitude = position.coords.latitude;
        var longitude = position.coords.longitude;
  
        // create a hidden form and submit it with the latitude and longitude
        var form = document.createElement('form');
        form.method = 'POST';
        form.action = '{% url "pages:my_view" %}';
        form.style.display = 'none';
  
        var latInput = document.createElement('input');
        latInput.type = 'hidden';
        latInput.name = 'latitude';
        latInput.value = latitude;
  
        var longInput = document.createElement('input');
        longInput.type = 'hidden';
        longInput.name = 'longitude';
        longInput.value = longitude;
  
        form.appendChild(latInput);
        form.appendChild(longInput);
        document.body.appendChild(form);
        console.log(form)
        console.error(longitude)
        form.submit();
      });
    } else {
      console.log('Geolocation is not supported by this browser.');
    }
  }
</script>

templates/post_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<body onload="getLocation()">

  <div class="card mx-auto" style="width:500px">
    <div class="card-header">
      <h1>New post</h1>
    </div>
    <div class="card-body">
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy}}
      </form>
    </div>
    <div class="card-footer">
      <button class="btn btn-primary ml-2" type="submit" href="{% url 'pages:post_history' %}">Post</button>
    </div>
  </div>
  
<script>
  function getLocation() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(showPosition);
    } else {
      console.log("Geolocation is not supported by this browser.");
    }
  }
  
  function showPosition(position) {
    let lat = position.coords.latitude;
    let long = position.coords.longitude;
    document.getElementById("id_latitude").value = lat;
    document.getElementById("id_longitude").value = long;
  };
</script>
{% endblock content %}

templates/signin.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block metadescription %}
	Sign in.
{% endblock %}
{% block title %}
	Login
{% endblock %}
{% block content %}
	<div class="container">
		<br>
		<h1 class="my_title text-center">Login or Create a New Account</h1>
		<br>
		<div class="row">
			<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center my_custom_div">
				<br>
				<h2 class="my_title">New User?</h2>
				<br>
				<a href="{% url 'signup' %}" class="btn btn-secondary">Create New Account</a>



				{% comment %} <a href="{% provider_login_url 'google' %}">Login With Google</a> {% endcomment %}
			</div>
			<div class="col-12 col-sm-12 col-md-12 col-lg-6 bg-light">
				<div>
					<br>
					<h2 class="my_title">Users Only</h2>
					<form method="post">
						{% csrf_token %}
						<p>{{ form | crispy }}</p>
						<button type="submit" class="btn btn-secondary">Login</button>
					</form>
					<br>
				</div>
				
			</div>
		</div>
		<br>
	</div>
	<br>
{% endblock %}

templates/signup.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block metadescription %}
	Sign up.
{% endblock %}
{% block title %}
{% endblock %}
{% block content %}
	<div>
		{% if not form.is_valid %}
			<div class="mx-auto">
				<br>
				<h1 class="my_title text-center">Create a new account</h1>
				<br>
				<div class="col-9 col-sm-9 col-md-6 col-lg-5 mx-auto bg-light">
					<br>
					<p>Enter the following information to create a new account.</p>
					<form method="post">
						<p>{{ form | crispy }}</p>
						{% csrf_token %}
						<button type="submit" class="btn btn-secondary">Register Account</button>
					</form>
					<br>
				</div>
			</div>
		{% else %}
			<div class="mx-auto">
				<br>
				<h1 class="my_title text-center">Your account has been successfully created</h1>
				<br>
				<div>
					<p>
						Your account has been created and it is ready to use.
						<br>
					</p>
				</div>
			</div>

		{% endif %}
	</div>
	<br>
{% endblock %}